// Code generated by Kelpie. DO NOT EDIT.
package requester

import (
	"github.com/adamconnelly/kelpie"
	"github.com/adamconnelly/kelpie/mocking"
	. "net/http"
	"io"
)

type Mock struct {
	mocking.Mock
	instance Instance
}

func NewMock() *Mock {
	mock := Mock{
		instance: Instance{},
	}
	mock.instance.mock = &mock

	return &mock
}

type Instance struct {
	mock *Mock
}

func (m *Instance) MakeRequest(r *Request) (r0 io.Reader, r1 error) {
	expectation := m.mock.Call("MakeRequest", r)
	if expectation != nil {
		if expectation.ObserveFn != nil {
			observe := expectation.ObserveFn.(func(r *Request) (io.Reader, error))
			return observe(r)
		}

		if expectation.PanicArg != nil {
			panic(expectation.PanicArg)
		}

		if expectation.Returns[0] != nil {
			r0 = expectation.Returns[0].(io.Reader)
		}

		if expectation.Returns[1] != nil {
			r1 = expectation.Returns[1].(error)
		}
	}

	return
}

func (m *Mock) Instance() *Instance {
	return &m.instance
}

type MakeRequestMethodMatcher struct {
	matcher mocking.MethodMatcher
}

func (m *MakeRequestMethodMatcher) CreateMethodMatcher() *mocking.MethodMatcher {
	return &m.matcher
}

func MakeRequest[P0 *Request | mocking.Matcher[*Request]](r P0) *MakeRequestMethodMatcher {
	result := MakeRequestMethodMatcher{
		matcher: mocking.MethodMatcher{
			MethodName:       "MakeRequest",
			ArgumentMatchers: make([]mocking.ArgumentMatcher, 1),
		},
	}

	if matcher, ok := any(r).(mocking.Matcher[*Request]); ok {
		result.matcher.ArgumentMatchers[0] = matcher
	} else {
		result.matcher.ArgumentMatchers[0] = kelpie.ExactMatch(any(r).(*Request))
	}

	return &result
}

type MakeRequestTimes struct {
	matcher *MakeRequestMethodMatcher
}

// Times allows you to restrict the number of times a particular expectation can be matched.
func (m *MakeRequestMethodMatcher) Times(times uint) *MakeRequestTimes {
	m.matcher.Times = &times

	return &MakeRequestTimes{
		matcher: m,
	}
}

// Once specifies that the expectation will only match once.
func (m *MakeRequestMethodMatcher) Once() *MakeRequestTimes {
	return m.Times(1)
}

// Never specifies that the method has not been called. This is mainly useful for verification
// rather than mocking.
func (m *MakeRequestMethodMatcher) Never() *MakeRequestTimes {
	return m.Times(0)
}

// Return returns the specified results when the method is called.
func (t *MakeRequestTimes) Return(r0 io.Reader, r1 error) *MakeRequestAction {
	return &MakeRequestAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			Returns:       []any{r0, r1},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (t *MakeRequestTimes) Panic(arg any) *MakeRequestAction {
	return &MakeRequestAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (t *MakeRequestTimes) When(observe func(r *Request) (io.Reader, error)) *MakeRequestAction {
	return &MakeRequestAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			ObserveFn:     observe,
		},
	}
}

func (t *MakeRequestTimes) CreateMethodMatcher() *mocking.MethodMatcher {
	return &t.matcher.matcher
}

// Return returns the specified results when the method is called.
func (m *MakeRequestMethodMatcher) Return(r0 io.Reader, r1 error) *MakeRequestAction {
	return &MakeRequestAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			Returns:       []any{r0, r1},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (m *MakeRequestMethodMatcher) Panic(arg any) *MakeRequestAction {
	return &MakeRequestAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (m *MakeRequestMethodMatcher) When(observe func(r *Request) (io.Reader, error)) *MakeRequestAction {
	return &MakeRequestAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			ObserveFn:     observe,
		},
	}
}

type MakeRequestAction struct {
	expectation mocking.Expectation
}

func (a *MakeRequestAction) CreateExpectation() *mocking.Expectation {
	return &a.expectation
}
