// Code generated by Kelpie. DO NOT EDIT.
package storage

import (
	"github.com/adamconnelly/kelpie"
	"github.com/adamconnelly/kelpie/mocking"
)

type Mock struct {
	mocking.Mock
	instance instance
}

func NewMock() *Mock {
	mock := Mock{
		instance: instance{},
	}
	mock.instance.mock = &mock

	return &mock
}

type instance struct {
	mock *Mock
}

func (m *instance) StoreConfigValue(key string, value string) (r0 error) {
	expectation := m.mock.Call("StoreConfigValue", key, value)
	if expectation != nil {
		if expectation.ObserveFn != nil {
			observe := expectation.ObserveFn.(func(key string, value string) error)
			return observe(key, value)
		}

		if expectation.PanicArg != nil {
			panic(expectation.PanicArg)
		}

		if expectation.Returns[0] != nil {
			r0 = expectation.Returns[0].(error)
		}
	}

	return
}

func (m *Mock) Instance() *instance {
	return &m.instance
}

type storeConfigValueMethodMatcher struct {
	matcher mocking.MethodMatcher
}

func (m *storeConfigValueMethodMatcher) CreateMethodMatcher() *mocking.MethodMatcher {
	return &m.matcher
}

func StoreConfigValue[P0 string | mocking.Matcher[string], P1 string | mocking.Matcher[string]](key P0, value P1) *storeConfigValueMethodMatcher {
	result := storeConfigValueMethodMatcher{
		matcher: mocking.MethodMatcher{
			MethodName:       "StoreConfigValue",
			ArgumentMatchers: make([]mocking.ArgumentMatcher, 2),
		},
	}

	if matcher, ok := any(key).(mocking.Matcher[string]); ok {
		result.matcher.ArgumentMatchers[0] = matcher
	} else {
		result.matcher.ArgumentMatchers[0] = kelpie.ExactMatch(any(key).(string))
	}

	if matcher, ok := any(value).(mocking.Matcher[string]); ok {
		result.matcher.ArgumentMatchers[1] = matcher
	} else {
		result.matcher.ArgumentMatchers[1] = kelpie.ExactMatch(any(value).(string))
	}

	return &result
}

type storeConfigValueTimes struct {
	matcher *storeConfigValueMethodMatcher
}

// Times allows you to restrict the number of times a particular expectation can be matched.
func (m *storeConfigValueMethodMatcher) Times(times uint) *storeConfigValueTimes {
	m.matcher.Times = &times

	return &storeConfigValueTimes{
		matcher: m,
	}
}

// Once specifies that the expectation will only match once.
func (m *storeConfigValueMethodMatcher) Once() *storeConfigValueTimes {
	return m.Times(1)
}

// Never specifies that the method has not been called. This is mainly useful for verification
// rather than mocking.
func (m *storeConfigValueMethodMatcher) Never() *storeConfigValueTimes {
	return m.Times(0)
}

// Return returns the specified results when the method is called.
func (t *storeConfigValueTimes) Return(r0 error) *storeConfigValueAction {
	return &storeConfigValueAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (t *storeConfigValueTimes) Panic(arg any) *storeConfigValueAction {
	return &storeConfigValueAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (t *storeConfigValueTimes) When(observe func(key string, value string) error) *storeConfigValueAction {
	return &storeConfigValueAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			ObserveFn:     observe,
		},
	}
}

func (t *storeConfigValueTimes) CreateMethodMatcher() *mocking.MethodMatcher {
	return &t.matcher.matcher
}

// Return returns the specified results when the method is called.
func (m *storeConfigValueMethodMatcher) Return(r0 error) *storeConfigValueAction {
	return &storeConfigValueAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (m *storeConfigValueMethodMatcher) Panic(arg any) *storeConfigValueAction {
	return &storeConfigValueAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (m *storeConfigValueMethodMatcher) When(observe func(key string, value string) error) *storeConfigValueAction {
	return &storeConfigValueAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			ObserveFn:     observe,
		},
	}
}

type storeConfigValueAction struct {
	expectation mocking.Expectation
}

func (a *storeConfigValueAction) CreateExpectation() *mocking.Expectation {
	return &a.expectation
}
