// Code generated by Kelpie. DO NOT EDIT.
package registrationservice

import (
	"github.com/adamconnelly/kelpie"
	"github.com/adamconnelly/kelpie/mocking"
)

type Mock struct {
	mocking.Mock
	instance Instance
}

func NewMock() *Mock {
	mock := Mock{
		instance: Instance{},
	}
	mock.instance.mock = &mock

	return &mock
}

type Instance struct {
	mock *Mock
}

// Register registers the item with the specified name.
func (m *Instance) Register(name string) (r0 error) {
	expectation := m.mock.Call("Register", name)
	if expectation != nil {
		if expectation.ObserveFn != nil {
			observe := expectation.ObserveFn.(func(name string) error)
			return observe(name)
		}

		if expectation.PanicArg != nil {
			panic(expectation.PanicArg)
		}

		if expectation.Returns[0] != nil {
			r0 = expectation.Returns[0].(error)
		}
	}

	return
}

func (m *Mock) Instance() *Instance {
	return &m.instance
}

type RegisterMethodMatcher struct {
	matcher mocking.MethodMatcher
}

func (m *RegisterMethodMatcher) CreateMethodMatcher() *mocking.MethodMatcher {
	return &m.matcher
}

// Register registers the item with the specified name.
func Register[P0 string | mocking.Matcher[string]](name P0) *RegisterMethodMatcher {
	result := RegisterMethodMatcher{
		matcher: mocking.MethodMatcher{
			MethodName:       "Register",
			ArgumentMatchers: make([]mocking.ArgumentMatcher, 1),
		},
	}

	if matcher, ok := any(name).(mocking.Matcher[string]); ok {
		result.matcher.ArgumentMatchers[0] = matcher
	} else {
		result.matcher.ArgumentMatchers[0] = kelpie.ExactMatch(any(name).(string))
	}

	return &result
}

type RegisterTimes struct {
	matcher *RegisterMethodMatcher
}

// Times allows you to restrict the number of times a particular expectation can be matched.
func (m *RegisterMethodMatcher) Times(times uint) *RegisterTimes {
	m.matcher.Times = &times

	return &RegisterTimes{
		matcher: m,
	}
}

// Once specifies that the expectation will only match once.
func (m *RegisterMethodMatcher) Once() *RegisterTimes {
	return m.Times(1)
}

// Never specifies that the method has not been called. This is mainly useful for verification
// rather than mocking.
func (m *RegisterMethodMatcher) Never() *RegisterTimes {
	return m.Times(0)
}

// Return returns the specified results when the method is called.
func (t *RegisterTimes) Return(r0 error) *RegisterAction {
	return &RegisterAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (t *RegisterTimes) Panic(arg any) *RegisterAction {
	return &RegisterAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (t *RegisterTimes) When(observe func(name string) error) *RegisterAction {
	return &RegisterAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			ObserveFn:     observe,
		},
	}
}

func (t *RegisterTimes) CreateMethodMatcher() *mocking.MethodMatcher {
	return &t.matcher.matcher
}

// Return returns the specified results when the method is called.
func (m *RegisterMethodMatcher) Return(r0 error) *RegisterAction {
	return &RegisterAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (m *RegisterMethodMatcher) Panic(arg any) *RegisterAction {
	return &RegisterAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (m *RegisterMethodMatcher) When(observe func(name string) error) *RegisterAction {
	return &RegisterAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			ObserveFn:     observe,
		},
	}
}

type RegisterAction struct {
	expectation mocking.Expectation
}

func (a *RegisterAction) CreateExpectation() *mocking.Expectation {
	return &a.expectation
}
