// Code generated by Kelpie. DO NOT EDIT.
package registrationservice

import (
	"github.com/adamconnelly/kelpie"
	"github.com/adamconnelly/kelpie/mocking"
)

type Mock struct {
	mocking.Mock
	instance instance
}

func NewMock() *Mock {
	mock := Mock{
		instance: instance{},
	}
	mock.instance.mock = &mock

	return &mock
}

type instance struct {
	mock *Mock
}

// Register registers the item with the specified name.
func (m *instance) Register(name string) (r0 error) {
	expectation := m.mock.Call("Register", name)
	if expectation != nil {
		if expectation.ObserveFn != nil {
			observe := expectation.ObserveFn.(func(name string) error)
			return observe(name)
		}

		if expectation.PanicArg != nil {
			panic(expectation.PanicArg)
		}

		if expectation.Returns[0] != nil {
			r0 = expectation.Returns[0].(error)
		}
	}

	return
}

func (m *Mock) Instance() *instance {
	return &m.instance
}

type registerMethodMatcher struct {
	matcher mocking.MethodMatcher
}

func (m *registerMethodMatcher) CreateMethodMatcher() *mocking.MethodMatcher {
	return &m.matcher
}

// Register registers the item with the specified name.
func Register[P0 string | mocking.Matcher[string]](name P0) *registerMethodMatcher {
	result := registerMethodMatcher{
		matcher: mocking.MethodMatcher{
			MethodName:       "Register",
			ArgumentMatchers: make([]mocking.ArgumentMatcher, 1),
		},
	}

	if matcher, ok := any(name).(mocking.Matcher[string]); ok {
		result.matcher.ArgumentMatchers[0] = matcher
	} else {
		result.matcher.ArgumentMatchers[0] = kelpie.ExactMatch(any(name).(string))
	}

	return &result
}

type registerTimes struct {
	matcher *registerMethodMatcher
}

// Times allows you to restrict the number of times a particular expectation can be matched.
func (m *registerMethodMatcher) Times(times uint) *registerTimes {
	m.matcher.Times = &times

	return &registerTimes{
		matcher: m,
	}
}

// Once specifies that the expectation will only match once.
func (m *registerMethodMatcher) Once() *registerTimes {
	return m.Times(1)
}

// Never specifies that the method has not been called. This is mainly useful for verification
// rather than mocking.
func (m *registerMethodMatcher) Never() *registerTimes {
	return m.Times(0)
}

// Return returns the specified results when the method is called.
func (t *registerTimes) Return(r0 error) *registerAction {
	return &registerAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (t *registerTimes) Panic(arg any) *registerAction {
	return &registerAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (t *registerTimes) When(observe func(name string) error) *registerAction {
	return &registerAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			ObserveFn:     observe,
		},
	}
}

func (t *registerTimes) CreateMethodMatcher() *mocking.MethodMatcher {
	return &t.matcher.matcher
}

// Return returns the specified results when the method is called.
func (m *registerMethodMatcher) Return(r0 error) *registerAction {
	return &registerAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (m *registerMethodMatcher) Panic(arg any) *registerAction {
	return &registerAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (m *registerMethodMatcher) When(observe func(name string) error) *registerAction {
	return &registerAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			ObserveFn:     observe,
		},
	}
}

type registerAction struct {
	expectation mocking.Expectation
}

func (a *registerAction) CreateExpectation() *mocking.Expectation {
	return &a.expectation
}
