// Code generated by Kelpie. DO NOT EDIT.
package maths

import (
	"github.com/adamconnelly/kelpie"
	"github.com/adamconnelly/kelpie/mocking"
)

type Mock struct {
	mocking.Mock
	instance Instance
}

func NewMock() *Mock {
	mock := Mock{
		instance: Instance{},
	}
	mock.instance.mock = &mock

	return &mock
}

type Instance struct {
	mock *Mock
}

func (m *Instance) Add(a int, b int) (r0 int) {
	expectation := m.mock.Call("Add", a, b)
	if expectation != nil {
		if expectation.ObserveFn != nil {
			observe := expectation.ObserveFn.(func(a int, b int) int)
			return observe(a, b)
		}

		if expectation.PanicArg != nil {
			panic(expectation.PanicArg)
		}

		if expectation.Returns[0] != nil {
			r0 = expectation.Returns[0].(int)
		}
	}

	return
}

func (m *Instance) ParseInt(input string) (r0 int, r1 error) {
	expectation := m.mock.Call("ParseInt", input)
	if expectation != nil {
		if expectation.ObserveFn != nil {
			observe := expectation.ObserveFn.(func(input string) (int, error))
			return observe(input)
		}

		if expectation.PanicArg != nil {
			panic(expectation.PanicArg)
		}

		if expectation.Returns[0] != nil {
			r0 = expectation.Returns[0].(int)
		}

		if expectation.Returns[1] != nil {
			r1 = expectation.Returns[1].(error)
		}
	}

	return
}

func (m *Mock) Instance() *Instance {
	return &m.instance
}

type AddMethodMatcher struct {
	matcher mocking.MethodMatcher
}

func (m *AddMethodMatcher) CreateMethodMatcher() *mocking.MethodMatcher {
	return &m.matcher
}

func Add[P0 int | mocking.Matcher[int], P1 int | mocking.Matcher[int]](a P0, b P1) *AddMethodMatcher {
	result := AddMethodMatcher{
		matcher: mocking.MethodMatcher{
			MethodName:       "Add",
			ArgumentMatchers: make([]mocking.ArgumentMatcher, 2),
		},
	}

	if matcher, ok := any(a).(mocking.Matcher[int]); ok {
		result.matcher.ArgumentMatchers[0] = matcher
	} else {
		result.matcher.ArgumentMatchers[0] = kelpie.ExactMatch(any(a).(int))
	}

	if matcher, ok := any(b).(mocking.Matcher[int]); ok {
		result.matcher.ArgumentMatchers[1] = matcher
	} else {
		result.matcher.ArgumentMatchers[1] = kelpie.ExactMatch(any(b).(int))
	}

	return &result
}

type AddTimes struct {
	matcher *AddMethodMatcher
}

// Times allows you to restrict the number of times a particular expectation can be matched.
func (m *AddMethodMatcher) Times(times uint) *AddTimes {
	m.matcher.Times = &times

	return &AddTimes{
		matcher: m,
	}
}

// Once specifies that the expectation will only match once.
func (m *AddMethodMatcher) Once() *AddTimes {
	return m.Times(1)
}

// Never specifies that the method has not been called. This is mainly useful for verification
// rather than mocking.
func (m *AddMethodMatcher) Never() *AddTimes {
	return m.Times(0)
}

// Return returns the specified results when the method is called.
func (t *AddTimes) Return(r0 int) *AddAction {
	return &AddAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (t *AddTimes) Panic(arg any) *AddAction {
	return &AddAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (t *AddTimes) When(observe func(a int, b int) int) *AddAction {
	return &AddAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			ObserveFn:     observe,
		},
	}
}

func (t *AddTimes) CreateMethodMatcher() *mocking.MethodMatcher {
	return &t.matcher.matcher
}

// Return returns the specified results when the method is called.
func (m *AddMethodMatcher) Return(r0 int) *AddAction {
	return &AddAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (m *AddMethodMatcher) Panic(arg any) *AddAction {
	return &AddAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (m *AddMethodMatcher) When(observe func(a int, b int) int) *AddAction {
	return &AddAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			ObserveFn:     observe,
		},
	}
}

type AddAction struct {
	expectation mocking.Expectation
}

func (a *AddAction) CreateExpectation() *mocking.Expectation {
	return &a.expectation
}

type ParseIntMethodMatcher struct {
	matcher mocking.MethodMatcher
}

func (m *ParseIntMethodMatcher) CreateMethodMatcher() *mocking.MethodMatcher {
	return &m.matcher
}

func ParseInt[P0 string | mocking.Matcher[string]](input P0) *ParseIntMethodMatcher {
	result := ParseIntMethodMatcher{
		matcher: mocking.MethodMatcher{
			MethodName:       "ParseInt",
			ArgumentMatchers: make([]mocking.ArgumentMatcher, 1),
		},
	}

	if matcher, ok := any(input).(mocking.Matcher[string]); ok {
		result.matcher.ArgumentMatchers[0] = matcher
	} else {
		result.matcher.ArgumentMatchers[0] = kelpie.ExactMatch(any(input).(string))
	}

	return &result
}

type ParseIntTimes struct {
	matcher *ParseIntMethodMatcher
}

// Times allows you to restrict the number of times a particular expectation can be matched.
func (m *ParseIntMethodMatcher) Times(times uint) *ParseIntTimes {
	m.matcher.Times = &times

	return &ParseIntTimes{
		matcher: m,
	}
}

// Once specifies that the expectation will only match once.
func (m *ParseIntMethodMatcher) Once() *ParseIntTimes {
	return m.Times(1)
}

// Never specifies that the method has not been called. This is mainly useful for verification
// rather than mocking.
func (m *ParseIntMethodMatcher) Never() *ParseIntTimes {
	return m.Times(0)
}

// Return returns the specified results when the method is called.
func (t *ParseIntTimes) Return(r0 int, r1 error) *ParseIntAction {
	return &ParseIntAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			Returns:       []any{r0, r1},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (t *ParseIntTimes) Panic(arg any) *ParseIntAction {
	return &ParseIntAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (t *ParseIntTimes) When(observe func(input string) (int, error)) *ParseIntAction {
	return &ParseIntAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			ObserveFn:     observe,
		},
	}
}

func (t *ParseIntTimes) CreateMethodMatcher() *mocking.MethodMatcher {
	return &t.matcher.matcher
}

// Return returns the specified results when the method is called.
func (m *ParseIntMethodMatcher) Return(r0 int, r1 error) *ParseIntAction {
	return &ParseIntAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			Returns:       []any{r0, r1},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (m *ParseIntMethodMatcher) Panic(arg any) *ParseIntAction {
	return &ParseIntAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (m *ParseIntMethodMatcher) When(observe func(input string) (int, error)) *ParseIntAction {
	return &ParseIntAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			ObserveFn:     observe,
		},
	}
}

type ParseIntAction struct {
	expectation mocking.Expectation
}

func (a *ParseIntAction) CreateExpectation() *mocking.Expectation {
	return &a.expectation
}
