// Code generated by Kelpie. DO NOT EDIT.
package interfacefilter

import (
	"github.com/adamconnelly/kelpie"
	"github.com/adamconnelly/kelpie/mocking"
)

type Mock struct {
	mocking.Mock
	instance instance
}

func NewMock() *Mock {
	mock := Mock{
		instance: instance{},
	}
	mock.instance.mock = &mock

	return &mock
}

type instance struct {
	mock *Mock
}

// Include indicates that the specified interface should be included in the set of interfaces
// to generate.
func (m *instance) Include(name string) (r0 bool) {
	expectation := m.mock.Call("Include", name)
	if expectation != nil {
		if expectation.ObserveFn != nil {
			observe := expectation.ObserveFn.(func(name string) bool)
			return observe(name)
		}

		if expectation.PanicArg != nil {
			panic(expectation.PanicArg)
		}

		if expectation.Returns[0] != nil {
			r0 = expectation.Returns[0].(bool)
		}
	}

	return
}

func (m *Mock) Instance() *instance {
	return &m.instance
}

type includeMethodMatcher struct {
	matcher mocking.MethodMatcher
}

func (m *includeMethodMatcher) CreateMethodMatcher() *mocking.MethodMatcher {
	return &m.matcher
}

// Include indicates that the specified interface should be included in the set of interfaces
// to generate.
func Include[P0 string | mocking.Matcher[string]](name P0) *includeMethodMatcher {
	result := includeMethodMatcher{
		matcher: mocking.MethodMatcher{
			MethodName:       "Include",
			ArgumentMatchers: make([]mocking.ArgumentMatcher, 1),
		},
	}

	if matcher, ok := any(name).(mocking.Matcher[string]); ok {
		result.matcher.ArgumentMatchers[0] = matcher
	} else {
		result.matcher.ArgumentMatchers[0] = kelpie.ExactMatch(any(name).(string))
	}

	return &result
}

type includeTimes struct {
	matcher *includeMethodMatcher
}

// Times allows you to restrict the number of times a particular expectation can be matched.
func (m *includeMethodMatcher) Times(times uint) *includeTimes {
	m.matcher.Times = &times

	return &includeTimes{
		matcher: m,
	}
}

// Once specifies that the expectation will only match once.
func (m *includeMethodMatcher) Once() *includeTimes {
	return m.Times(1)
}

// Never specifies that the method has not been called. This is mainly useful for verification
// rather than mocking.
func (m *includeMethodMatcher) Never() *includeTimes {
	return m.Times(0)
}

// Return returns the specified results when the method is called.
func (t *includeTimes) Return(r0 bool) *includeAction {
	return &includeAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (t *includeTimes) Panic(arg any) *includeAction {
	return &includeAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (t *includeTimes) When(observe func(name string) bool) *includeAction {
	return &includeAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			ObserveFn:     observe,
		},
	}
}

func (t *includeTimes) CreateMethodMatcher() *mocking.MethodMatcher {
	return &t.matcher.matcher
}

// Return returns the specified results when the method is called.
func (m *includeMethodMatcher) Return(r0 bool) *includeAction {
	return &includeAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			Returns:       []any{r0},
		},
	}
}

// Panic panics using the specified argument when the method is called.
func (m *includeMethodMatcher) Panic(arg any) *includeAction {
	return &includeAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (m *includeMethodMatcher) When(observe func(name string) bool) *includeAction {
	return &includeAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			ObserveFn:     observe,
		},
	}
}

type includeAction struct {
	expectation mocking.Expectation
}

func (a *includeAction) CreateExpectation() *mocking.Expectation {
	return &a.expectation
}
