// Code generated by Kelpie. DO NOT EDIT.
package doublenestedservice

import (
	"github.com/adamconnelly/kelpie/mocking"
)

type Mock struct {
	mocking.Mock
	instance instance
}

func NewMock() *Mock {
	mock := Mock{
		instance: instance{},
	}
	mock.instance.mock = &mock

	return &mock
}

type instance struct {
	mock *Mock
}

func (m *instance) DoSomething() {
	expectation := m.mock.Call("DoSomething")
	if expectation != nil {
		if expectation.ObserveFn != nil {
			observe := expectation.ObserveFn.(func())
			observe()
			return
		}

		if expectation.PanicArg != nil {
			panic(expectation.PanicArg)
		}
	}

	return
}

func (m *Mock) Instance() *instance {
	return &m.instance
}

type doSomethingMethodMatcher struct {
	matcher mocking.MethodMatcher
}

func (m *doSomethingMethodMatcher) CreateMethodMatcher() *mocking.MethodMatcher {
	return &m.matcher
}

func DoSomething() *doSomethingMethodMatcher {
	result := doSomethingMethodMatcher{
		matcher: mocking.MethodMatcher{
			MethodName:       "DoSomething",
			ArgumentMatchers: make([]mocking.ArgumentMatcher, 0),
		},
	}

	return &result
}

type doSomethingTimes struct {
	matcher *doSomethingMethodMatcher
}

// Times allows you to restrict the number of times a particular expectation can be matched.
func (m *doSomethingMethodMatcher) Times(times uint) *doSomethingTimes {
	m.matcher.Times = &times

	return &doSomethingTimes{
		matcher: m,
	}
}

// Once specifies that the expectation will only match once.
func (m *doSomethingMethodMatcher) Once() *doSomethingTimes {
	return m.Times(1)
}

// Never specifies that the method has not been called. This is mainly useful for verification
// rather than mocking.
func (m *doSomethingMethodMatcher) Never() *doSomethingTimes {
	return m.Times(0)
}

// Panic panics using the specified argument when the method is called.
func (t *doSomethingTimes) Panic(arg any) *doSomethingAction {
	return &doSomethingAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (t *doSomethingTimes) When(observe func()) *doSomethingAction {
	return &doSomethingAction{
		expectation: mocking.Expectation{
			MethodMatcher: &t.matcher.matcher,
			ObserveFn:     observe,
		},
	}
}

func (t *doSomethingTimes) CreateMethodMatcher() *mocking.MethodMatcher {
	return &t.matcher.matcher
}

// Panic panics using the specified argument when the method is called.
func (m *doSomethingMethodMatcher) Panic(arg any) *doSomethingAction {
	return &doSomethingAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			PanicArg:      arg,
		},
	}
}

// When calls the specified observe callback when the method is called.
func (m *doSomethingMethodMatcher) When(observe func()) *doSomethingAction {
	return &doSomethingAction{
		expectation: mocking.Expectation{
			MethodMatcher: &m.matcher,
			ObserveFn:     observe,
		},
	}
}

type doSomethingAction struct {
	expectation mocking.Expectation
}

func (a *doSomethingAction) CreateExpectation() *mocking.Expectation {
	return &a.expectation
}
